### ISSUE TITLE
Make it easier to see in the UI which extensions are added and enabled/disabled at different configuration levels

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/extensions-client-common#40]
It's tedious to figure out at which level of configuration an extension is enabled/disabled/added. If there were some small UI (such as the "Ext" popup in the bottom right) that showed all of this information, there would probably be less confusion such as:

- https://github.com/sourcegraph/sourcegraph/issues/13223
- https://sourcegraph.slack.com/archives/C07KZF47K/p1536860019000100

**Comment by sqs** [comment]
The immediate issue is that the "Extensions" link is hidden, so he couldn't even see the *current* way we have to see this info. I think it's premature to think about more ways to display this info, when the current way to show this info was intentionally hidden from him for now. (See https://github.com/sourcegraph/sourcegraph/issues/13223#issuecomment-421135742 on the private repo.)

**Comment by chrismwendt** [comment]
This is less pressing now that client settings have been removed and the UI has been revamped.
